additional_docs: null
chunk_overlap: 500
chunk_size: 2500
description: Map_Reduce_1_Prompt_Age
emb_type: text-embedding-ada-002
ground_truth: uc_gt.csv
llm_type: gpt-4
max_tokens: 1024
pinecone_index_name: null
project: uc
prompt: individual_prompts.py
temperature: 0
test_case: /mnt/c/Users/QUAN/Desktop/medical-chatbot/data/queries/uc.txt
vectorstore: /mnt/c/Users/QUAN/Desktop/medical-chatbot/data/emb_store/uc/faiss/text-embedding-ada-002/v5-add-tables_2500_500
verbose: true
