# General Settings
project: uc
test_case: data/queries/uc_all.txt
prompt: uc_qa_source_ground.py
ground_truth: uc_all_gt.csv
description: Chat_Ground_Tables_Chunk-size=1000_Overlap=200_Doc=10_Max-token=6500_Stuff
verbose: True

# Embedding Settings
emb_type: text-embedding-ada-002
vectorstore: faiss/text-embedding-ada-002/v7-add-tables_1000_200
chunk_size: 1000
chunk_overlap: 200
additional_docs: data/additional_docs.json
max_tokens_limit: 6500
no_returned_docs: 10
reduce_k_below_max_tokens: True
chain_type: stuff
pinecone_index_name:

# LLM Settings
llm_type: gpt-4
temperature: 0
max_tokens: 1024