additional_docs: data/additional_docs.json
chain_type: map_reduce
chunk_overlap: 500
chunk_size: 5000
collapse_llm: gpt-3.5-turbo-16k
collapse_max_doc_tokens: 6000
collapse_max_gen_tokens: 1024
combine_max_doc_tokens: 14000
combine_max_gen_tokens: 1024
description: gpt-3.5_Map_Reduce_Chunk_Stuff_5000_500
document_level: chunk
ground_truth: uc_gt.csv
llm_type: gpt-3.5-turbo
max_gen_tokens: 1024
project: uc
prompt: uc_qa_map_reduce_1.py
reduce_llm: gpt-3.5-turbo-16k
temperature: 0
test_case: data/queries/uc.txt
verbose: false
yaml_cfg: exps/map_reduce_1.yaml
